services:
  frontend:
    build: 
      context: ./frontend
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - pnpm-store:/pnpm/store
    command: npx next dev

  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - ./backend:/app
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container:
  pnpm-store:
  
